name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Docker compose build
        run: docker-compose up --build --abort-on-container-exit --exit-code-from builder
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}